### ISSUE TITLE
System Programming Case Study

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/wikibook-project#29]
I would really love a chapter that goes through famous examples of bugs and breaks them down. The reason that programmers get paid so much isn't to code, to implement documentation, or to include tests, it is to interpret the requirements and anticipate bugs that would cost millions of dollars. This would provide for a nice `why?` in terms of each topic in systems.

https://github.com/danluu/post-mortems

https://en.wikipedia.org/wiki/List_of_software_bugs

Off the top of my head

* [x] Heartbleed
* [x] Shellshock
* [x] Dirty COW
* [x] Meltdown
* [x] Spectre
* [x] Portsmash

**Comment by aneeshdurg** [comment]
We have a lecture about spectre/meltdown in the honors lectures. I'll try to dig it up when I've got some free time.

**Comment by bhuvy2** [comment]
Closed with the latest commit, would still welcome the honors lecture.
